[package]
authors = ["Machtan <jako3047@gmail.com>"]
name = "glorious"
version = "0.1.0"

[dependencies]
sdl2 = { path = "../rust-sdl2" }
sdl2_image = { path = "../rust-sdl2_image" }
sdl2_ttf = { path = "../rust-sdl2_ttf" }
sdl2_mixer = { path = "../rust-sdl2_mixer" }
